config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :event_filters, except: %i(index show)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  root to: 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_topics, dependent: :destroy
  has_many :topics, through: :event_topics
  has_many :event_notifications, dependent: :destroy

  validates :name, :city, :start_date, :end_date, :topics, presence: true
  validate :end_date_more_than_start_date

  after_create :schedule_event_notification

  private

  def end_date_more_than_start_date
    return if start_date.blank? || end_date.blank?

    if start_date >= end_date
      errors.add(:end_date, 'Must be greater than Start date')
    end
  end

  def schedule_event_notification
    EventNotificationWorker.perform_async(id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i(show edit update destroy)

  def index
    @events_carrier = EventsCarrier.new(current_user, event_filter_params)
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :city, topic_ids: [])
  end

  def event_filter_params
    if params[:event_filter].present?
      params.require(:event_filter).permit(:name, :start_date_begin, :start_date_end, :city, :topic_id)
    else
      {}
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_topics(event)
    event.topics.order(:name).pluck(:name).join(', ')
  end
end

app/views/events/_event_filter.html.haml
= simple_form_for carrier.event_filter do |f|
  = f.input :city, collection: carrier.cities_collection
  = f.input :start_date_begin,
            as: :string,
            input_html: { class: 'js-start-date', value: formatted_date(f.object.start_date_begin) }
  = f.input :start_date_end,
            as: :string,
            input_html: { class: 'js-end-date', value: formatted_date(f.object.start_date_end) }
  = f.association :topic, as: :select, collection: carrier.topics_collection

  = link_to 'Search',
            'javascript:void(0);',
            class: 'btn btn-primary js-event-filter-btn',
            data: { url: events_path }
  = f.button :submit, 'Save filter', class: 'btn btn-default'
  = link_to 'Clear filter', events_path

app/views/events/_form.html.haml
= simple_form_for event do |f|
  - if event.errors.any?
    #error-explanation
      %h2 #{pluralize(event.errors.count, 'error')} prohibited this event from being saved:
      %ul
        - event.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name, required: true
  = f.input :city, required: true
  = f.input :start_date,
            as: :string,
            required: true,
            input_html: { class: 'js-start-date', value: formatted_date(event.start_date) }
  = f.input :end_date,
            as: :string,
            required: true,
            input_html: { class: 'js-end-date', value: formatted_date(event.end_date) }
  = f.association :topics, as: :check_boxes, required: true

  = f.button :submit, class: 'btn btn-primary'

app/views/events/edit.html.haml
.row
  .col-xs-4
    %h1 Editing event

.row
  .col-xs-4
    = render partial: 'form', locals: { event: @event }

.row
  .col-xs-4
    = link_to 'Show', @event
    \|
    = link_to 'To events', events_path

app/views/events/index.html.haml
.row
  .col-xs-8
    %h1 Listing events

    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Name
          %th Start date
          %th End date
          %th City
          %th Topics
          %th
          %th
          %th

      %tbody
        - @events_carrier.events.each do |event|
          %tr
            %td= event.name
            %td= formatted_date(event.start_date)
            %td= formatted_date(event.end_date)
            %td= event.city
            %td= event_topics(event)
            %td= link_to 'Show', event
            %td= link_to 'Edit', edit_event_path(event)
            %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

    %br

    = link_to 'New Event', new_event_path, class: 'btn btn-primary'

  .col-xs-4
    .row
      .col-xs-12
        %h3 Filters
        = render partial: 'event_filter', locals: { carrier: @events_carrier.event_filter_carrier }

    %br

    .row
      .col-xs-12
        %h4 Saved filters:
        - @events_carrier.saved_event_filters.each do |event_filter|
          %div
            = link_to event_filter.name,
                      events_path(@events_carrier.event_filter_filtering_params(event_filter))
            = link_to event_filter do
              %span.glyphicon.glyphicon-edit{ 'aria-hidden' => true }
            = link_to event_filter, method: :delete, data: { confirm: 'Are you sure?' } do
              %span.glyphicon.glyphicon-remove{ 'aria-hidden' => true }

app/views/events/new.html.haml
.row
  .col-xs-4
    %h1 New event

.row
  .col-xs-4
    = render partial: 'form', locals: { event: @event }

.row
  .col-xs-4
    = link_to 'To events', events_path

app/views/events/show.html.haml
%p
  %b Name:
  = @event.name
%p
  %b Start date:
  = formatted_date(@event.start_date)
%p
  %b End date:
  = formatted_date(@event.end_date)
%p
  %b City:
  = @event.city
%p
  %b Topics:
  = event_topics(@event)

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'To events', events_path